# Path to the text file containing the list of file paths
file.list.path=C:/Users/sairam/sairam1/SRAVAN TCS/filelist.txt

# Path to the backup folder
backup.folder.path=C:/Users/sairam/OneDrive/Desktop/backup
